# Basic Python

## 1. Split this string

In [1]:
s = "Hi there Sam!"

In [2]:
s="Hi there Sam!"
x=s.split()
print(x)

['Hi', 'there', 'Sam!']


## 2. Use .format() to print the following string. 

### Output should be: The diameter of Earth is 12742 kilometers.

In [ ]:
planet = "Earth"
diameter = 12742

In [3]:
planet = "Earth"
diameter = 12742
print( 'The diameter of {} is {} kilometers.' .format(planet,diameter));

The diameter of Earth is 12742 kilometers.


## 3. In this nest dictionary grab the word "hello"

In [ ]:
d = {'k1':[1,2,3,{'tricky':['oh','man','inception',{'target':[1,2,3,'hello']}]}]}

In [4]:
d = {'k1':[1,2,3,{'tricky':['oh','man','inception',{'target':[1,2,3,'hello']}]}]}
print(d['k1'][3]["tricky"][3]['target'][3])

hello


# Numpy

In [ ]:
import numpy as np

## 4.1 Create an array of 10 zeros? 
## 4.2 Create an array of 10 fives?

In [5]:
import numpy as np
array=np.zeros(10)
print("An array of 10 zeros:")
print(array)

An array of 10 zeros:
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [6]:
import numpy as np
array=np.ones(10)*5
print("An array of 10 fives:")
print(array)

An array of 10 fives:
[5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]


## 5. Create an array of all the even integers from 20 to 35

In [7]:
import numpy as np
array=np.arange(20,35,2)
print("Array of all the even integers from 20 to 35")
print(array)

Array of all the even integers from 20 to 35
[20 22 24 26 28 30 32 34]


## 6. Create a 3x3 matrix with values ranging from 0 to 8

In [13]:
import numpy as np
x =  np.arange(0, 8).reshape(3,3)
print(x)

ValueError: ignored

## 7. Concatenate a and b 
## a = np.array([1, 2, 3]), b = np.array([4, 5, 6])

In [14]:
a=np.array([1,2,3]);
print(a)
b=np.array([4,5,6]);
print(b)
print(np.concatenate((a,b)))

[1 2 3]
[4 5 6]
[1 2 3 4 5 6]


# Pandas

## 8. Create a dataframe with 3 rows and 2 columns

In [ ]:
import pandas as pd


In [19]:

import pandas as pd
import numpy as np
arrayA=['f','d','g']
arrayB=['1','2','3']
arrayC=[4,5,6]
pd.Dataframe(np.array([arrayA,arrayB,arrayC ]),column=["AA","NN","GG"])


AttributeError: ignored

## 9. Generate the series of dates from 1st Jan, 2023 to 10th Feb, 2023

In [20]:
year = int(input("Input a year: "))

if (year % 400 == 0):
    leap_year = True
elif (year % 100 == 0):
    leap_year = False
elif (year % 4 == 0):
    leap_year = True
else:
    leap_year = False

month = int(input("Input a month [1-12]: "))

if month in (1, 3, 5, 7, 8, 10, 12):
    month_length = 31
elif month == 2:
    if leap_year:
        month_length = 29
    else:
        month_length = 28
else:
    month_length = 30


day = int(input("Input a day [1-31]: "))

if day < month_length:
    day += 1
else:
    day = 1
    if month == 12:
        month = 1
        year += 1
    else:
        month += 1
print("The next date is [yyyy-mm-dd] %d-%d-%d." % (year, month, day))

Input a year: 2023
Input a month [1-12]: 1-2


ValueError: ignored

## 10. Create 2D list to DataFrame

lists = [[1, 'aaa', 22],
         [2, 'bbb', 25],
         [3, 'ccc', 24]]

In [ ]:
lists = [[1, 'aaa', 22], [2, 'bbb', 25], [3, 'ccc', 24]]